workflows:
  android-apk:
    name: Android APK (Expo prebuild)
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 20
        CI: 1
      node: 20
      java: 17
      xcode: 15.1
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - $CM_BUILD_DIR/frontend/node_modules
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: ".*"
          include: true
          source: true
    scripts:
      - name: Show environment
        script: |
          node -v
          npm -v || true
          yarn -v || true
          java -version
          echo "Working dir: $CM_BUILD_DIR"
          ls -la
          echo "Frontend dir contents:" && ls -la frontend
      - name: Clean caches (Metro & Gradle)
        script: |
          cd frontend
          rm -rf .metro-cache || true
          rm -rf node_modules/.cache || true
          cd android
          ./gradlew clean --no-daemon || true
      - name: Install dependencies
        script: |
          cd frontend
          rm -f package-lock.json
          yarn install --non-interactive --frozen-lockfile
          npx expo --version || (echo "Expo CLI not found via npx" && exit 1)
          node -e "require.resolve('expo/package.json')" || (echo "Expo package not installed" && exit 1)
          test -f babel.config.js || (echo "Missing frontend/babel.config.js" && exit 1)
      - name: Expo prebuild (Android)
        script: |
          export CI=1
          cd frontend
          npx expo prebuild --platform android --clean
      - name: Build APK (with logs)
        script: |
          set -o pipefail
          cd frontend/android
          ./gradlew assembleRelease --no-daemon --stacktrace --info | tee gradle-build.log
          echo "Problems report (if any):"
          if [ -f build/reports/problems/problems-report.html ]; then
            ls -la build/reports/problems
          fi
    artifacts:
      - frontend/android/app/build/outputs/apk/release/*.apk
      - frontend/android/gradle-build.log
    publishing:
      email:
        recipients:
          - thomas1290@gmx.net
        notify:
          success: true
          failure: true